import { simpleGit, type SimpleGit } from 'simple-git';

/**
 * Git side effects for the remediation workflow, behind an interface so the
 * orchestrator can be unit-tested without a real repository. Implementations
 * operate on a working directory (the throwaway clone). Never force-pushes.
 */
export interface GitRunner {
  currentBranch(dir: string): Promise<string>;
  hasLocalBranch(dir: string, branch: string): Promise<boolean>;
  /** Create+checkout (when `create`) or checkout an existing branch. */
  switchToBranch(dir: string, branch: string, create: boolean): Promise<void>;
  stageAll(dir: string): Promise<void>;
  /** Unified diff of the staged changes (for dry-run review). */
  diffStaged(dir: string): Promise<string>;
  commit(dir: string, message: string): Promise<void>;
  ensureRemote(dir: string, name: string, url: string): Promise<void>;
  push(dir: string, remote: string, branch: string): Promise<void>;
}

/**
 * `git -c` config that routes GitHub auth through the `gh` CLI so pushes are
 * non-interactive — without this, `git push` over HTTPS prompts for a password
 * on the terminal, which deadlocks inside the TUI. Because gh supplies the token
 * before git would ever prompt, the push never blocks on input. The empty first
 * entry clears any pre-existing helper so we always use gh's token.
 */
export const GH_CREDENTIAL_CONFIG = [
  'credential.helper=',
  'credential.https://github.com.helper=!gh auth git-credential',
];

/** simple-git options that enable gh-credential routing and a stall timeout. */
export const FIX_GIT_OPTIONS = {
  config: GH_CREDENTIAL_CONFIG,
  // Our credential-helper value is a fixed constant (gh), not user input.
  unsafe: { allowUnsafeCredentialHelper: true },
  // Backstop: abort (with an error) if a git task stalls, instead of hanging forever.
  timeout: { block: 120_000 },
} as const;

/** A simple-git bound to `dir` with gh-credential routing and a stall timeout. */
function gitFor(dir: string): SimpleGit {
  return simpleGit(dir, FIX_GIT_OPTIONS);
}

export const defaultGitRunner: GitRunner = {
  async currentBranch(dir) {
    return (await gitFor(dir).revparse(['--abbrev-ref', 'HEAD'])).trim();
  },
  async hasLocalBranch(dir, branch) {
    const branches = await gitFor(dir).branchLocal();
    return branches.all.includes(branch);
  },
  async switchToBranch(dir, branch, create) {
    const git = gitFor(dir);
    if (create) await git.checkoutLocalBranch(branch);
    else await git.checkout(branch);
  },
  async stageAll(dir) {
    await gitFor(dir).add(['--all']);
  },
  async diffStaged(dir) {
    return gitFor(dir).diff(['--staged']);
  },
  async commit(dir, message) {
    await gitFor(dir).commit(message);
  },
  async ensureRemote(dir, name, url) {
    const git = gitFor(dir);
    const remotes = await git.getRemotes(true);
    const existing = remotes.find((r) => r.name === name);
    if (existing) {
      if (existing.refs.push !== url) await git.remote(['set-url', name, url]);
    } else {
      await git.addRemote(name, url);
    }
  },
  async push(dir, remote, branch) {
    // Set upstream, never force; auth via gh, never prompt (see gitFor).
    await gitFor(dir).push(remote, branch, ['--set-upstream']);
  },
};

/** Branch name for a fix: `spiderwebs/fix-<package>-<version>` (filesystem/ref-safe). */
export function fixBranchName(packageName: string, version: string): string {
  const pkg = packageName
    .replace(/^@/, '')
    .replace(/[/\\]/g, '-')
    .replace(/[^\w.-]/g, '-');
  const ver = version.replace(/[^\w.-]/g, '-');
  return `spiderwebs/fix-${pkg}-${ver}`;
}

/** Conventional-commit message that references the resolved advisories + findings. */
export function fixCommitMessage(input: {
  packageName: string;
  fromVersion: string;
  toVersion: string;
  advisoryIds: readonly string[];
  findingIds: readonly string[];
}): string {
  const advisories = input.advisoryIds.length ? input.advisoryIds.join(', ') : 'known advisories';
  return (
    `fix(deps): bump ${input.packageName} from ${input.fromVersion} to ${input.toVersion}\n\n` +
    `Resolves ${advisories}.\n` +
    `SpiderWebs finding ids: ${input.findingIds.join(', ')}.\n\n` +
    `Generated by SpiderWebs (defensive dependency remediation).`
  );
}
