import { describe, expect, it } from 'vitest';
import {
  FIX_GIT_OPTIONS,
  GH_CREDENTIAL_CONFIG,
  fixBranchName,
  fixCommitMessage,
} from '../src/fix/git.js';
import {
  buildPrBody,
  buildPrTitle,
  forkCloneUrl,
  parseRepoCoordinates,
} from '../src/fix/github.js';
import { resolveTarget } from '../src/ingest.js';
import type { FixPlan } from '../src/fix/planner.js';

const plan: FixPlan = {
  packageName: 'lodash',
  ecosystem: 'npm',
  fromVersion: '4.17.20',
  toVersion: '4.17.21',
  manifestPath: 'package.json',
  lockfilePath: 'package-lock.json',
  manager: 'npm',
  field: 'dependencies',
  currentRange: '^4.17.20',
  newRange: '^4.17.21',
  rangeRewritten: false,
  resolvesFindingIds: ['sw-0000000000000000'],
  resolvesAdvisoryIds: ['GHSA-35jh-r3h4-6jhm', 'CVE-2021-23337'],
};

describe('fixBranchName', () => {
  it('builds a ref-safe branch and flattens scoped names', () => {
    expect(fixBranchName('lodash', '4.17.21')).toBe('spiderwebs/fix-lodash-4.17.21');
    expect(fixBranchName('@babel/core', '7.20.0')).toBe('spiderwebs/fix-babel-core-7.20.0');
  });
});

describe('non-interactive auth (prevents TUI push hangs)', () => {
  it('routes GitHub auth through the gh CLI credential helper', () => {
    expect(GH_CREDENTIAL_CONFIG).toContain(
      'credential.https://github.com.helper=!gh auth git-credential',
    );
    expect(FIX_GIT_OPTIONS.config).toBe(GH_CREDENTIAL_CONFIG);
  });

  it('enables the credential helper and caps stalls so git never hangs forever', () => {
    expect(FIX_GIT_OPTIONS.unsafe.allowUnsafeCredentialHelper).toBe(true);
    expect(FIX_GIT_OPTIONS.timeout.block).toBeGreaterThan(0);
  });
});

describe('fixCommitMessage', () => {
  it('references advisories and finding ids and identifies SpiderWebs', () => {
    const msg = fixCommitMessage({
      packageName: 'lodash',
      fromVersion: '4.17.20',
      toVersion: '4.17.21',
      advisoryIds: ['CVE-2021-23337'],
      findingIds: ['sw-abc'],
    });
    expect(msg).toContain('bump lodash from 4.17.20 to 4.17.21');
    expect(msg).toContain('CVE-2021-23337');
    expect(msg).toContain('sw-abc');
    expect(msg).toContain('Generated by SpiderWebs');
  });
});

describe('parseRepoCoordinates', () => {
  it.each([
    ['acme/widgets', { owner: 'acme', repo: 'widgets' }],
    ['https://github.com/acme/widgets', { owner: 'acme', repo: 'widgets' }],
    ['git@github.com:acme/widgets.git', { owner: 'acme', repo: 'widgets' }],
  ])('%s', (target, coords) => {
    expect(parseRepoCoordinates(resolveTarget(target))).toEqual(coords);
  });

  it('returns undefined for non-GitHub targets', () => {
    expect(parseRepoCoordinates(resolveTarget('/local/path'))).toBeUndefined();
  });
});

describe('forkCloneUrl', () => {
  it('builds an https clone url', () => {
    expect(forkCloneUrl({ owner: 'me', repo: 'widgets' })).toBe(
      'https://github.com/me/widgets.git',
    );
  });
});

describe('buildPrTitle / buildPrBody', () => {
  it('title states the version delta', () => {
    expect(buildPrTitle(plan)).toBe('fix(deps): bump lodash from 4.17.20 to 4.17.21');
  });

  it('body lists advisories and self-identifies', () => {
    const body = buildPrBody(plan);
    expect(body).toContain('GHSA-35jh-r3h4-6jhm');
    expect(body).toContain('lodash');
    expect(body).toContain('SpiderWebs');
  });

  it('body warns on a major-version bump', () => {
    const body = buildPrBody({ ...plan, fromVersion: '0.21.1', toVersion: '1.6.8' });
    expect(body).toContain('breaking changes');
  });
});
